### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-app#1]
Thanks for the app ^^

I would have prefer to have all the link on the main page and not in a menu. 
The idea was : people open the app and directly see where to go, not more complex, if they want to read more they just scroll down. 

As the webpage is only in english, how can it be translate it ? i can do the French one.

**Comment by NeoTheThird** [comment]
The newest version comes with text links on the homepage, if that's what you mean. I agree, it is a little easier to find what's important that way.

Translations are a different topic. Our pipeline for translations is not yet set up, so i can't really comment on that yet. I created #3 to track progress on that.

Thank you for your proposal :)
