### ISSUE TITLE
Devices Link

### ISSUE THREAD

**Issue by Gabriele69** [ubports/ubports-app#16]
Hello.
The App link to the devices points to the old page of the site and not the new (beautiful) one.

G

**Comment by NeoTheThird** [comment]
> old page and not the new (beautiful) one.

That hurts :'(

Just kidding :D I'll check it out. When the link was implemented, the new devices page wasn't finished yet (Actually, it still isn't completely as there are some constraints with the api for the installer that is provided by the old page). I'll check and set up a redirect as soon as necessary.

**Comment by NeoTheThird** [comment]
I just removed the devices link, because it caused the menu to overflow in landscape mode. If you think about it, it's also not really necessary, since the app users already know, what hardware is available.
