### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-app#3]
Find a way for users to contribute translations.

**Comment by Anne017** [comment]
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translations could be more easily reviewed by Ubuntu Translators?

**Comment by NeoTheThird** [comment]
That might be an option. We should look into this issue and decide for a singular method for all core apps.

**Comment by pacomolinero** [comment]
My es.po for app
[es.po.zip](https://github.com/ubports/ubports-app/files/1088738/es.po.zip)

**Comment by NeoTheThird** [comment]
@pacomolinero Thanks, i will merge it.

**Comment by pacomolinero** [comment]
Sorry but I do not know how to request a pull. Here is the review of es-po file
[es.po.zip](https://github.com/ubports/ubports-app/files/1090427/es.po.zip)

**Comment by pacomolinero** [comment]
Finally I try a pull request, and I hope was fine

**Comment by NeoTheThird** [comment]
@Flohack74 is looking into setting up Weblate for UBports, so we'll be able to close this soon.
